business_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
#path function defines a url pattern
#'' is empty to represent based path to app
# views.index is the function defined in views.py
# name='index' parameter is to dynamically create url
# example in html <a href="{% url 'index' %}">Home</a>.
path('', views.index, name='index'),

# Add Django site authentication urls (for login, logout, password management)
path('accounts/', include('django.contrib.auth.urls')),
path('accounts/register/', views.RegisterPage, name='register_page'),
path('accounts/logout_successful', views.LoggedOut, name='logged-out'),
path('accounts/login_successful', views.LoggedIn, name='logged-in'),

path('sessions/', views.SessionListView.as_view(), name='sessions'),
path('session/create', views.CreateSession, name='create-session'),
path('session/<session_id>/update/', views.UpdateSession, name='update-session'),
path('session/<session_id>/delete/', views.DeleteSession, name='delete-session'),
path('session/<pk>', views.SessionDetailView.as_view(), name='session-detail'),

path('schedule/', views.ViewSchedule, name='view-schedule'),

path('appointment/', include('appointment.urls')),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # connect path to portfolio_app urls
    path('', include('business_app.urls'))
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
]

business_app/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User

# Create your models here.

class Session(models.Model):

    #List of choices for major value in database, human readable name
    LENGTH = (
    ('30', '30 minute session'),
    ('45', '45 minute session'),
    ('60', '60 minute session'),
    ('75', '75 minute session'),
    ('90', '90 minute session'),
    ('120', '120 minute session'),
    )
    name = models.CharField(max_length=200)
    description = models.TextField()
    length = models.CharField(max_length=20, choices=LENGTH)
    price = models.PositiveSmallIntegerField(validators=[MaxValueValidator(10000)])
    is_active = models.BooleanField()

    # For creating a user account
    # user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    #Define default String to return the name for representing the Model object."
    def __str__(self):
        return self.name

    #Returns the URL to access a particular instance of MyModelName.
    #if you define this method then Django will automatically
    # add a "View on Site" button to the model's record editing screens in the Admin site
    def get_absolute_url(self):
        return reverse('session-detail', args=[str(self.id)])
 
class CalendarEvent(models.Model):

    name = models.CharField(max_length=200)

    session = models.ForeignKey(Session, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

business_app/forms.py
from django.forms import ModelForm
from .models import Session
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


#create class for Session form
class SessionForm(ModelForm):
    class Meta:
        model = Session
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta: 
        model = User
        fields = ['username', 'email', 'password1', 'password2']

business_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.views.generic import ListView, DetailView
from .forms import *
from django.contrib import messages
from django.contrib.auth.models import Group, User
from django.contrib.auth.decorators import login_required
from appointment.models import Service




# Create your views here.
def index(request):
    # Render the HTML template index.html with the
    # data in the context variable.
    return render ( request, 'business_app/index.html')


# login and logout views
# def login(request):
#     return render (request, 'login.html')

def LoggedIn(request):
    return render (request, 'registration/login_successful.html')

def LoggedOut(request):
    return render (request, 'registration/logout_successful.html')

# View for user registration page
def RegisterPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()

            messages.success(request, 'Account was created for '+ username)
            print("user was supposedly created")
            return redirect('login')
        
        else: print("form is not valid?")

    context = {'form':form}
    return render(request, 'registration/register.html', context)

# Views for CRUD pages
class SessionListView(ListView):
    model = Session

class SessionDetailView(DetailView):
    model = Session

@login_required
def CreateSession(request):
    """CreateSession displays the form to add a new session
    """
    form = SessionForm()

    if request.method == 'POST':
        form = SessionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('sessions')
        
    context={'form':form}
    return render(request, 'business_app/session_form.html', context)

@login_required
def UpdateSession(request, session_id):
    """UpdateSession displays the form to edit an existing session
    """
    session = Session.objects.get(id=session_id)
    form = SessionForm(instance=session)

    if request.method == 'POST':
        form = SessionForm(request.POST, instance=session)
        if form.is_valid():
            form.save()
            return redirect('session-detail', session_id)
    
    context={'form':form}
    return render(request, 'business_app/session_form.html', context)

@login_required
def DeleteSession(request, session_id):
    """DeleteSession displays the form to delete an existing session
    """
    session = Session.objects.get(id=session_id)

    if request.method == 'POST':
        session.delete()
        messages.success(request, "The session has been deleted.")

        return redirect('sessions')
    
    context = {'item': session, 'session_id':session_id}
    return render(request, 'business_app/session_confirm_delete.html', context)

def ViewSchedule(request):
    return render(request, 'appointment\\appointments.html')
    

business_app/templates/business_app/base_template.html
{% load static %}
{% load i18n %}


<!DOCTYPE html>
<html lang="en">

<style>
  .footer {
     position: fixed;
     left: 0;
     bottom: 0;
     width: 100%;
     height: 50px;
     background: linear-gradient(White, LightSkyBlue);
     color: black;
     text-align: center;
  }
</style>

 <head>
  <title>{% block title %}Massage Therapy{% endblock title %}</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <script src=
   "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js">
    </script>

    <!-- Stylesheets -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- Custom CSS-->

    {% block customCSS %}{% endblock %}
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap"
        rel="stylesheet">
    {% block scriptHead %}{% endblock %}
  </head>

 <body>
   <div class="container-fluid">

     <!-- Navbar-->
     <nav class="navbar navbar-expand-sm bg-body-tertiary">
       <div class="container-fluid">
        <a href="{% url 'index' %}"> <img src="{% static 'images\massage_icon_small.png' %}"> </a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNav">
           <ul class="navbar-nav">
             <!--  {% url 'index' %}  is defined in url path to dynamically create url -->
             <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
             <a class="nav-link" href="{% url 'sessions' %}">Sessions</a>
             <a class="nav-link" href="{{ '/appointment/request/1' }}">Schedule</a>
            </ul>
            <ul class="navbar-nav ms-auto">
             {% if user.is_authenticated %}

                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <input class="btn btn-outline" type="submit" value="Log out">
                  </a>
                </form>

             {% else %}
               <a class="nav-link" href="{% url 'login' %}">Therapist Login</a>
             {% endif %} 
            </ul>
         </div>
       </div>
     </nav>

     <div class="col-sm-10">
        <!-- add block content from html template -->
        {% block content %}
        {% endblock %}

        {% block body %}
        {% endblock %}
        
        <!--====== Javascript & Jquery ======-->
        <!-- Ion Icons -->
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
                integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
                crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js"
                integrity="sha512-WW8/jxkELe2CAiE4LvQfwm1rajOS8PHasCCx+knHG0gBHt8EXxS6T6tJRTGuDQVnluuAvMxWF4j8SNFDKceLFg=="
                crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        {% block customJS %}{% endblock %}
        
     </div>
    
     <footer class="footer"> 
      <div> Business name goes here </div>
     </footer> 

     </div>
   </div>
 </body>
</html>

business_app/templates/business_app/index.html
<!-- inherit from base.html-->
{% extends "business_app/base_template.html" %}

<!-- Replace block content in base_template.html -->
{% block content %}
<div class="main">
    <h2>Welcome to the new massage therapy page</h2>
    <p> </p>
    <h4>Where we can do more for you</h4>
    <p> </p>
</div>
<a href="{% url 'sessions' %}" class="btn btn-outline-secondary"><h5>Click here to view sessions</h5></a>
{% endblock %}

business_app/templates/business_app/session_confirm_delete.html
{% extends "business_app/base_template.html" %}
{% block title %}Delete Session{% endblock %}

{% block content %}

<h1>Delete Session</h1>

<p>Are you sure you want to delete {{ item.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" class="btn btn-outline-danger" value="Yes, delete">
  <a href="{% url 'session-detail' session_id %}" class="btn btn-outline-secondary">Cancel</a>
</form>

{% endblock %}

business_app/templates/business_app/session_detail.html
<!-- inherit from base.html-->
{% extends "business_app/base_template.html" %}
{% block title %}{{ session.name }}{% endblock %}

<style> 
    .btn {
        color: #000000;
        border-color: warning;
    }
</style>

<!-- Replace block content in base_template.html -->
{% block content %}
<h1>{{ session.name }}</h1>

{% if user.is_authenticated %}
    <a href="{% url 'update-session' session.id %}" class="btn btn-outline-warning" role="btn">Update</a>
    <a href="{% url 'delete-session' session.id %}" class="btn btn-outline-danger" role="button">Delete</a>    
{% endif %}
<p> </p>
<p><strong>Length:</strong> {{ session.get_length_display }}</p>
<p><strong>Details:</strong> {{ session.description }}</p>
<p><strong>Price:</strong> ${{ session.price }}</p>
<p><strong>Is the session active?</strong> {{ session.is_active }}

</p>

   
{% endblock %}

business_app/templates/business_app/session_form.html
{% extends "business_app/base_template.html" %}
{% block title %}Save Session{% endblock %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {% if session.name %}
    <h1>Edit {{ session.name }}</h1>
  {% else %}
    <h1>Create new session</h1>
  {% endif %}
  <p> </p>
  {% comment %} {{form}} {% endcomment %}
  <table>
    {{ form.as_table }}
  </table> 
  <input type="submit" value="Submit" />
</form>
{% endblock %}

business_app/templates/business_app/session_list.html
<!-- inherit from base_template.html-->
{% extends "business_app/base_template.html" %}
{% block title %}Session List{% endblock %}

<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Session list</h1>

{% if user.is_authenticated %}
    <div class="create session">
        <a href="{% url 'create-session' %}" class="btn btn-outline-success" role="button">Create</a>
    </div>
{% endif %}
<p> </p>
<div class = "session-list-group">
    {% for session in session_list %}
        <div class="session-list-group-item p-3 border">
            <ul>
                <a href="{{ session.get_absolute_url }}">{{ session.name }}</a>  ${{session.price}}
            </ul>
        </div>
    {% endfor %}
</div>    


{%endblock%}

business_app/templates/business_app/view_schedule.html
{% extends "business_app/base_template.html" %}
{% block title %}Schedule{% endblock %}

{% block content %}

{% endblock %}